=== GenomicsStandardsConsortium/mixs-ng/mixs-profile-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "MiXS template schema",
    "type": "object",
    "additionalProperties": false,
    "required": [ "name", "description", "contact", "packages", "hierarchy" ],
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "contact": {
            "type": "object",
            "properties": {
		"organization": { "type": "string" },
		"organization_abbrev": { "type": "string" },
		"url": { "type": "string" },
		"email": { "type": "string" },
		"firstname": { "type": "string" },
		"lastname": { "type": "string" }
            },
            "additionalProperties": false,
            "required": [ "organization", "organization_abbrev", "email", "firstname", "lastname" ]
        },
        "packages": {
	    "type": "array",
	    "minItems": 1,
	    "uniqueItems": true,
	    "items": {
		"enum": [ "project", "sample", "library", "air", "built environment", "host-associated", "human-associated", "human-gut", "human-oral", "human-skin", "human-vagina", "microbial mat|biofilm", "miscellaneous", "plant-associated", "sediment", "soil", "wastewater|sludge", "water" ]
	    }
        },
	"fieldDefinitions": {
	    "type": "array",
	    "items": {
		"type": "object",
		"required": [ "field", "validation" ],
		"uniqueItems": true,
		"properties": {
		    "field": {
			"$ref": "#/definitions/fields"
		    },
		    "validation": {
			"type": "string"
		    },
		    "description": {
			"type": "string"
		    }
		}
	    }
	},
        "hierarchy": {
            "type": "array",
            "minItems": 1,
	    "maxItems": 3,
	    "items": {
		"type": "array",
		"minItems": 1,
		"uniqueItems": true,
		"items": {
		    "$ref": "#/definitions/fields"
		}
	    }
	}
    },
    "definitions": {
	"fields": {
	    "enum": [
		"project_name",
		"project_description",
		"project_funding",
		"PI_email",
		"PI_firstname",
		"PI_lastname",
		"PI_organization",
		"PI_organization_country",
		"PI_organization_address",
		"PI_organization_url",
		"email",
		"firstname",
		"lastname",
		"organization",
		"organization_country",
		"organization_address",
		"organization_url",
		"submitted_to_indsc",
		"envo_release",
		"quiime_id",
		"vamps_id",
		"ncbi_id",
		"greengenes_id",
		"sample_name",
		"latitude",
		"longitude",
		"continent",
		"country",
		"location",
		"depth",
		"altitude",
		"elevation",
		"temperature",
		"ph",
		"collection_date",
		"collection_time",
		"collection_timezone",
		"experimental_factor",
		"isol_growth_condt",
		"samp_collect_device",
		"samp_size",
		"samp_mat_process",
		"sample_strategy",
		"metagenome_taxonomy",
		"biome",
		"feature",
		"material",
		"env_package",
		"metagenome_name",
		"investigation_type",
		"seq_meth",
		"target_gene",
		"mrna_percent",
		"abs_air_humidity",
		"agrochem_addition",
		"air_temp",
		"air_temp_regm",
		"al_sat",
		"al_sat_meth",
		"alkalinity",
		"alkyl_diethers",
		"alt",
		"aminopept_act",
		"ammonium",
		"amniotic_fluid_color",
		"annual_season_precpt",
		"annual_season_temp",
		"antibiotic_regm",
		"atmospheric_data",
		"bac_prod",
		"bac_resp",
		"bacteria_carb_prod",
		"barometric_press",
		"biochem_oxygen_dem",
		"biomass",
		"birth_control",
		"bishomohopanol",
		"blood_blood_disord",
		"bromide",
		"build_occup_type",
		"building_setting",
		"calcium",
		"carb_dioxide",
		"carb_monoxide",
		"carb_nitro_ratio",
		"chem_administration",
		"chem_mutagen",
		"chem_oxygen_dem",
		"chloride",
		"chlorophyll",
		"climate_environment",
		"conduc",
		"crop_rotation",
		"cur_land_use",
		"cur_vegetation",
		"cur_vegetation_meth",
		"density",
		"dermatology_disord",
		"dew_point",
		"diet_last_six_month",
		"diether_lipids",
		"diss_carb_dioxide",
		"diss_hydrogen",
		"diss_inorg_carb",
		"diss_inorg_nitro",
		"diss_inorg_phosp",
		"diss_org_carb",
		"diss_org_nitro",
		"diss_oxygen",
		"dominant_hand",
		"douche",
		"down_par",
		"drainage_class",
		"drug_usage",
		"efficiency_percent",
		"elev",
		"emulsions",
		"extreme_event",
		"extreme_salinity",
		"fao_class",
		"fertilizer_regm",
		"filter_type",
		"fire",
		"flooding",
		"fluor",
		"foetal_health_stat",
		"fungicide_regm",
		"gaseous_environment",
		"gaseous_substances",
		"gastrointest_disord",
		"gestation_state",
		"glucosidase_act",
		"gravidity",
		"gravity",
		"growth_hormone_regm",
		"growth_med",
		"gynecologic_disord",
		"heat_cool_type",
		"heavy_metals",
		"heavy_metals_meth",
		"herbicide_regm",
		"horizon",
		"horizon_meth",
		"host_age",
		"host_blood_press_diast",
		"host_blood_press_syst",
		"host_body_habitat",
		"host_body_mass_index",
		"host_body_product",
		"host_body_site",
		"host_body_temp",
		"host_color",
		"host_common_name",
		"host_diet",
		"host_disease_stat",
		"host_dry_mass",
		"host_family_relationship",
		"host_genotype",
		"host_growth_cond",
		"host_height",
		"host_hiv_stat",
		"host_infra_specific_name",
		"host_infra_specific_rank",
		"host_last_meal",
		"host_length",
		"host_life_stage",
		"host_occupation",
		"host_phenotype",
		"host_pulse",
		"host_sex",
		"host_shape",
		"host_subject_id",
		"host_substrate",
		"host_taxid",
		"host_tot_mass",
		"host_wet_mass",
		"hrt",
		"humidity",
		"humidity_regm",
		"hysterectomy",
		"ihmc_ethnicity",
		"ihmc_medication_code",
		"indoor_space",
		"indoor_surf",
		"indust_eff_percent",
		"inorg_particles",
		"kidney_disord",
		"light_intensity",
		"light_type",
		"link_addit_analys",
		"link_class_info",
		"link_climate_info",
		"liver_disord",
		"local_class",
		"local_class_meth",
		"magnesium",
		"maternal_health_stat",
		"mean_frict_vel",
		"mean_peak_frict_vel",
		"mechanical_damage",
		"medic_hist_perform",
		"menarche",
		"menopause",
		"methane",
		"microbial_biomass",
		"microbial_biomass_meth",
		"mineral_nutr_regm",
		"misc_param",
		"n_alkanes",
		"nitrate",
		"nitrite",
		"nitro",
		"non_mineral_nutr_regm",
		"nose_mouth_teeth_throat_disord",
		"nose_throat_disord",
		"occup_samp",
		"occupant_dens_samp",
		"org_carb",
		"org_matter",
		"org_nitro",
		"org_particles",
		"organism_count",
		"oxy_stat_samp",
		"oxygen",
		"part_org_carb",
		"part_org_nitro",
		"particle_class",
		"perturbation",
		"pesticide_regm",
		"pet_farm_animal",
		"petroleum_hydrocarb",
		"ph_meth",
		"ph_regm",
		"phaeopigments",
		"phosphate",
		"phosplipid_fatt_acid",
		"photon_flux",
		"plant_body_site",
		"plant_product",
		"pollutants",
		"pool_dna_extracts",
		"porosity",
		"potassium",
		"pre_treatment",
		"pregnancy",
		"pressure",
		"previous_land_use",
		"previous_land_use_meth",
		"primary_prod",
		"primary_treatment",
		"profile_position",
		"pulmonary_disord",
		"radiation_regm",
		"rainfall_regm",
		"reactor_type",
		"redox_potential",
		"rel_air_humidity",
		"resp_part_matter",
		"salinity",
		"salinity_meth",
		"salt_regm",
		"samp_salinity",
		"samp_sort_meth",
		"samp_store_dur",
		"samp_store_loc",
		"samp_store_temp",
		"samp_vol_we_dna_ext",
		"season_environment",
		"secondary_treatment",
		"sediment_type",
		"sewage_type",
		"sexual_act",
		"sieving",
		"silicate",
		"slope_aspect",
		"slope_gradient",
		"sludge_retent_time",
		"smoker",
		"sodium",
		"soil_type",
		"soil_type_meth",
		"solar_irradiance",
		"soluble_inorg_mat",
		"soluble_org_mat",
		"soluble_react_phosp",
		"space_typ_state",
		"special_diet",
		"standing_water_regm",
		"store_cond",
		"study_complt_stat",
		"substructure_type",
		"sulfate",
		"sulfide",
		"surf_air_cont",
		"surf_humidity",
		"surf_material",
		"surf_moisture",
		"surf_moisture_ph",
		"surf_temp",
		"suspend_part_matter",
		"suspend_solids",
		"temp",
		"tertiary_treatment",
		"texture",
		"texture_meth",
		"tidal_stage",
		"tillage",
		"time_last_toothbrush",
		"time_since_last_wash",
		"tiss_cult_growth_med",
		"tot_carb",
		"tot_depth_water_col",
		"tot_diss_nitro",
		"tot_inorg_nitro",
		"tot_n_meth",
		"tot_nitro",
		"tot_org_c_meth",
		"tot_org_carb",
		"tot_part_carb",
		"tot_phosp",
		"tot_phosphate",
		"travel_out_six_month",
		"turbidity",
		"twin_sibling",
		"typ_occupant_dens",
		"urine_collect_meth",
		"urogenit_disord",
		"urogenit_tract_disor",
		"ventilation_rate",
		"ventilation_type",
		"volatile_org_comp",
		"wastewater_type",
		"water_content",
		"water_content_soil_meth",
		"water_current",
		"water_temp_regm",
		"watering_regm",
		"weight_loss_3_month",
		"wind_direction",
		"wind_speed"
	    ]
	}
    }
}

=== GenomicsStandardsConsortium/mixs-ng/mixs-profile.json
{
    "name": "MG-RAST MiXS",
    "description": "MG-RAST Minimum Information about any (X) Sequence",
    "contact": {
        "organization": "Argonne National Laboratory",
	"organization_abbrev": "ANL",
	"url": "http://metagenomics.anl.gov",
	"email": "info@mg-rast.org",
	"firstname": "Folker",
	"lastname": "Meyer"
    },
    "packages": [ "project", "sample", "library" ],
    "hierarchy":  [
	[ "project_name", "PI_email", "PI_firstname", "PI_lastname", "PI_organization", "PI_organization_country", "PI_organization_address", "latitude", "longitude", "country", "location", "collection_date", "collection_time", "collection_timezone", "sample_name", "metagenome_name", "investigation_type", "seq_meth" ]
    ]
}
